### ISSUE TITLE
Express golang code as a diagram

### ISSUE THREAD

**Issue by gedw99** [owulveryck/cue4puml4c4#19]
This high level architypes tool could also be used with actual golang code .

you could parse golang code and express it as Cue and render it into a structure .

by adding annotations to your golang you can then hint to the parser what it is .

Labels name examples such as service, data model, dto, etc etc 

so then in a live web server you can see the logical component structure of a large golang project . As you add label annotations the diagram would update 

You can take it further too and generate signalling code so that when the golang code is running you can see data flows in the diagram. 

Even further can you can step throw via the web gui by sending stop events from the web gui down into the golang program.

https://github.com/RussellLuo/kun Uses annotations in the golang code to kick off code generation and so could be used to add the things I discuss above .

now just because you could does not mean you should . 
but it makes golang code that teams work on more self describing and always produces component diagrams from the actual code . 

Would love to here what you think …

**Comment by owulveryck** [comment]
Hello,

first of all, thank you for raising this issue. There are a lot of very interesting things in it.

What would be the goal of the representation?
I am not sure whether CUE is a good intermediate representation. If we use a machine to parse the annotation, we can render an AST or another graph in memory. Then use this abstraction to feed a renderer.
(I made a set of articles on my blog where I create an in-memory graph based on RDF and render it with a set of templates).

If you have a use case, that could be fun to implement.

P.S. There is someone who also made a 3D representation of the go-routines (cannot find the reference anymore). But it is for runtime.

**Comment by gedw99** [comment]
About the 3D representation of the go-routines, i think i remember one that did it using webgl. Might ring a bell.

My background is as a systems architect, so my use case and goal to be able to represent and debug golang code using diagrams.  On really large projects with many teams, Model driven development is really useful to keep a high level overview of the code and its flow and pattern. I used different tools and ended up writing my own on some projects. Rational Rose was one i used. It sucked and we just did the code gen route and it worked great and the teams adopted it willingly. it was highly welcomed because the code generators removed a ton of plumbing code that is boring to write and maintain.

When i say debug i mean to just represent values travelling through the Model. Node based 3d systems do this, as well as node based CAD systems such as Rhino for Grasshopper. I mention this because the concept of visual representation and debugging carries over to many vertical markets.

I agree with your view parsing for AST is one part of the solution. Would be really cool to see the article where you used RDF to Render the graph model !!!

Typically you model and then gen, but you need partial classes for their custom code. Golang can do this easily with just package namespaces luckily and even more with golang tags ( which is like conditional compilation ). So its easy to do with golang.
Other way around is to parse the code and gen the Model.  Also useful and typically based on AST.

This is why i mentioned Kun its a code generator but also an Annotation parser. So you get the discovery and then the code generation.  You can parse the golang code for the annotations, and you can generate the signals because the code generator is simple golang templates. its sort of like telemetry. Using go build tags you can control if this telemetry is generated or not.
There is NO IR needed. I have used IR, and i found it too verbose and slow. Also its hard for others to work on it. But simple annotations and code generators are easy to understand. The signals would just be pumping via redis and into the GUI or something like that. Its stupid simple and efficient is my main point.  Its not fancy elegant.

SO in relation to Cue and this project, I was suggesting adding these concepts..
